### ISSUE TITLE
Persistance, partage et sauvegarde

### ISSUE THREAD

**Issue by tut-tuuut** [tut-tuuut/pajomatic#2]
Essayer https://github.com/tzi/url2form.js pour relier l'URL au contenu du formulaire.

**Comment by tut-tuuut** [comment]
Ça marche bien ! Merci @tzi ! :heart:

**Comment by tzi** [comment]
Trop cool! :smile: 
J'aime bien l'idée d'utiliser `history` API pour avoir l'url toujours à jour!
