### ISSUE TITLE
Lien vers l'accueil

### ISSUE THREAD

**Issue by astranchet** [tut-tuuut/pajomatic#36]
Sur un article de blog (par exemple celui [des congés payés](http://tut-tuuut.github.io/pajomatic//2016/05/09/conges-annee-incomplete.html)) le lien Pajomatic ne renvoie pas vers l'accueil du site mais vers une 404

**Comment by tut-tuuut** [comment]
Oh, bien vu ! Je m'occupe de ça  dès que je récupère un ordinateur.
