### ISSUE TITLE
Ajouter un readme.md

### ISSUE THREAD

**Issue by tut-tuuut** [tut-tuuut/pajomatic#6]
Il doit contenir : 
* [x] les instructions pour faire fonctionner jekyll
* [x] les consignes de contribution (en gros : PR propres, mergeables, unitaires)

**Comment by nicosomb** [comment]
:+1: 

dès que y'a ça, je teste ;-)

**Comment by tut-tuuut** [comment]
Presssssssion.
OK, je m'y mets.

**Comment by tut-tuuut** [comment]
Hello @nicosomb : j'ai ajouté un readme sur la branche master. Si tu galères à l'install, dis-moi… (Comme j'ai installé Ruby, bundler et Jekyll il y a très longtemps, j'ai un peu perdu la notion de la galère que c'est d'installer tout ça quand on n'est pas habitué !)
