### ISSUE TITLE
Controle sur les entrée utilisateurs

### ISSUE THREAD

**Issue by Guillaume-Rossignol** [tut-tuuut/pajomatic#7]
Certains champs comme 
* nombre de semaines par an d'accueil
* nombre de jour par semain d'accueil
* nombre de jour daccueil réel dans le mois

pourraient être bornés. Par contre, je ne sais pas si c'est du domaine du bug ou de l'amelioration de l'interface utilisateur.

**Comment by tut-tuuut** [comment]
Je me note de le faire pour "bientôt", ça ne coûte pas cher et ça permet d'éviter des erreurs. Merci. :)

**Comment by tut-tuuut** [comment]
C'est fait. Et s'il manque des règles, c'est hyper facile d'en ajouter. :)
